repos:
  - repo: local
    hooks:
      - id: eslint
        name: ESLint
        entry: npm run lint
        language: system
        files: \.ts$
        pass_filenames: false
      - id: test
        name: Run Tests
        entry: npm run test
        language: system
        pass_filenames: false